const AXIS_BACKGROUND_COLOR = colorant"#FAFCFF"
const GRID_COLOR = RGBAf(0.4, 0.4, 0.4, 0.20)
const SPINE_COLOR = :gray35
const PRIMARY_TEXT_COLOR = :gray20
const SECONDARY_TEXT_COLOR = :gray25
const MUTED_TEXT_COLOR = :gray35
const TERTIARY_TEXT_COLOR = :gray50
const AXIS_TEXT_COLOR = PRIMARY_TEXT_COLOR

const FIGURE_PADDING = (14, 14, 32, 14)
const FIGURE_WIDTH = 700

const AXIS_TITLE_GAP = 12
const BAR_LABEL_FONT_SIZE = 10
const CAPTION_X = 0.01
const CAPTION_Y = 0.01
const RUNTIME_SAMPLES_CAPTION = ""
const RUNTIME_BLOCKSIZE_CAPTION = ""
const MEMORY_CAPTION = "dark = CPU memory, light = GPU memory"
const MEMORY_BLOCK1000_CAPTION = "dark = CPU memory, light = GPU memory"

const GPU_PAIR_OFFSET = 0.20
const MEMORY_SINGLE_BAR_WIDTH = 0.78
const MEMORY_PAIRED_BAR_WIDTH = 0.32
const SAMPLE_JITTER = 0.1
const SAMPLE_MARKER_SIZE = 8
const DIAGONAL_TICK_LABEL_ROTATION = π / 4
const HORIZONTAL_TICK_LABEL_ROTATION = 0.0

const VALUE_LABEL_OFFSET_RATIO = 0.025
const GROUP_HEADER_Y_RATIO = 0.98

const TOP_FACTOR = 1.2

const RUNTIME_BEST_IMPL_MISSING_LABEL_X_RATIO = 0.02
const RUNTIME_BEST_IMPL_LABEL_X_OFFSET_RATIO = 0.025

const RUNTIME_GROUPED_BAR_OFFSET_SPAN = 0.35

const RUNTIME_BEST_IMPL_REF_LINE_WIDTH = 1.0
const MEMORY_FULL_ROW_GAP = 20
const MEMORY_DATASET_GROUP_ROW_GAP = 18

const GPU_MEMORY_LIGHTEN_FACTOR = 0.45
